# Generated by Django 3.1.7 on 2021-03-01 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210225_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(default='', max_length=200)),
                ('description', models.CharField(default='', max_length=2000)),
                ('image', models.ImageField(default='', upload_to='shop/image')),
            ],
        ),
    ]
